#!/usr/bin/env python3

# Register resources
import diagng.utils.gresources

from diagng.protocol.qualcomm.modules.log_manager import LogManager
from diagng.protocol.qualcomm.acquisition.base_input import (
    BaseQCDMInput,
    InputState,
)
from diagng.system.wireshark.wireshark_plugin_manager import (
    WiresharkPluginManager,
    PLUGIN_DIR,
)
from diagng.ui.qcdm_window.templates.wireshark_plugin_row import (
    WiresharkPluginRow,
)
from diagng.protocol.qualcomm.struct.diag_verno_f_req import DiagVernoFReq
from diagng.protocol.qualcomm.struct.diag_response import DiagResponse
from diagng.protocol.qualcomm.struct.diag_cmd_code import DiagCmdCode
from diagng.protocol.qualcomm.struct.diag_request import DiagRequest
from diagng.protocol.qualcomm.acquisition.dlf_input import DLFInput
from diagng.protocol.qualcomm.modules.ota_decoder import OTADecoder
from diagng.gobject.abstract.file_out_mode_selector import (
    FileOutModeSelector,
    FileOutMode,
)
from diagng.utils.kaitai_pretty_print import pretty_print_struct

from diagng.system.pcap_output import PcapOutput
from typing import Optional, Callable
from logging import info

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, GLib, Gio

DiagCmd = DiagCmdCode.DiagCmd


class InteractiveGUIFileOutModeSelector(FileOutModeSelector):
    output_file: Gio.File
    input_dialog: Gtk.Window

    def __init__(self, output_file: Gio.File, input_dialog: Gtk.Window):
        self.output_file = output_file
        self.input_dialog = input_dialog

    def query_file_out_mode(self, callback: Callable[[FileOutMode], None]):
        file_path = self.output_file.get_path()

        visible_file_path = file_path
        if visible_file_path.startswith('/run/user'):  # Flatpak-sandboxed path
            visible_file_path = visible_file_path.split('/').pop()

        def on_choose(dialog: Adw.AlertDialog, result: Gio.AsyncResult):
            result = dialog.choose_finish(result)

            callback(
                {
                    'dismiss': FileOutMode.Dismiss,
                    'append': FileOutMode.Append,
                    'overwrite': FileOutMode.Overwrite,
                }[result]
            )

        dialog = Adw.AlertDialog.new(
            '"%s" already exists' % visible_file_path,
            'Do you want to append to this file, or create a new one over it?',
        )
        dialog.set_heading_use_markup(False)
        dialog.add_response('dismiss', 'Dismiss')
        dialog.add_response('append', 'Append')
        dialog.add_response('overwrite', 'Overwrite')
        dialog.set_default_response('dismiss')
        dialog.set_close_response('dismiss')
        dialog.set_response_appearance(
            'append', Adw.ResponseAppearance.SUGGESTED
        )
        dialog.set_response_appearance(
            'overwrite', Adw.ResponseAppearance.DESTRUCTIVE
        )
        dialog.choose(self.input_dialog, None, on_choose)


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/qcdm_window/window-autogenerated.ui'
)
class QCDMWindow(Adw.Window):
    __gtype_name__ = 'QCDMWindow'

    ws_plugin_manager: WiresharkPluginManager
    plugin_watch_task: Gio.Cancellable

    input_obj: BaseQCDMInput
    log_manager: LogManager
    parent: Adw.ApplicationWindow
    qcdm_stack: Adw.ViewStack = Gtk.Template.Child()
    device_info_buffer: Gtk.TextBuffer = Gtk.Template.Child()

    wireshark_version_label: Gtk.Label = Gtk.Template.Child()

    ws_capture_row: Adw.ActionRow = Gtk.Template.Child()
    start_ws_capture_button: Gtk.Button = Gtk.Template.Child()
    stop_ws_capture_button: Gtk.Button = Gtk.Template.Child()

    pcap_capture_row: Adw.ActionRow = Gtk.Template.Child()
    pick_pcap_file_button: Gtk.Button = Gtk.Template.Child()
    stop_pcap_capture_button: Gtk.Button = Gtk.Template.Child()

    wireshark_plugins: Adw.PreferencesGroup = Gtk.Template.Child()

    wireshark_instance: Optional[PcapOutput] = None
    output_pcap: Optional[PcapOutput] = None

    def __init__(
        self, parent: Adw.ApplicationWindow, input_obj: BaseQCDMInput
    ):
        super().__init__()

        self.input_obj = input_obj
        self.parent = parent

        WIRESHARK_INFO_URL = 'https://github.com/P1sec/DiagNG/tree/main/src/diagng/system/wireshark'

        self.wireshark_plugins.set_description(
            (
                'A Wireshark plug-in will be installed in <a href="file://%s">%s</a> '
                + 'whenever you start a new capture, if not present. See <a href="%s">%s</a>'
            )
            % (
                GLib.markup_escape_text(PLUGIN_DIR),
                GLib.markup_escape_text(PLUGIN_DIR),
                GLib.markup_escape_text(WIRESHARK_INFO_URL),
                GLib.markup_escape_text(WIRESHARK_INFO_URL),
            )
        )

        self.ws_plugin_manager = WiresharkPluginManager()
        self.plugin_watch_task = self.ws_plugin_manager.watch_plugins()

        self.wireshark_plugins.bind_model(
            self.ws_plugin_manager.current_plugins,
            WiresharkPluginRow,
            self.ws_plugin_manager,
        )

        self.log_manager = LogManager(input_obj)

        # ==> TODO ⚠️ initialize logging when buttons
        # in the PCAP tab are clicked

        self.set_transient_for(parent)
        self.set_title(self.input_obj.full_name)
        self.input_obj.connect('notify::full-name', self.on_title_change)
        self.input_obj.connect('notify::state', self.on_state_change)
        self.present()

        self.on_state_change()
        if self.input_obj.state != InputState.Closed:
            self.gather_device_info()
        self.gather_wireshark_info()

        self.connect('close-request', self.on_quit)

    @Gtk.Template.Callback()
    def start_ws_capture_clicked(self, target: Gtk.Button, *args):

        def do_spawn(*args):
            # Spawn wireshark pipe, with flatpak-spawn if needed

            self.create_wireshark_pipe()

        if self.input_obj.state != InputState.Closed:
            # Enable network-related logs, if this is a live device

            self.log_manager.register_ota_related_logs(do_spawn)

            self.start_ws_capture_button.set_visible(False)
            self.stop_ws_capture_button.set_visible(True)
            self.ws_capture_row.set_activatable_widget(
                self.stop_ws_capture_button
            )
        else:
            # Just spawn Wireshark if this is a DLF file

            do_spawn()

    @Gtk.Template.Callback()
    def stop_ws_capture_clicked(self, target: Gtk.Button, *args):
        if self.wireshark_instance:
            self.wireshark_instance.close()
            self.wireshark_instance = None

    @Gtk.Template.Callback()
    def pick_pcap_file_clicked(self, target: Gtk.Button, *args):
        # Enable network-related logs

        def file_picked(file_dialog: Gtk.FileDialog, task: Gio.Task):

            try:
                open_result: Gio.File = file_dialog.save_finish(task)
            except GLib.GError as err:
                if err.message != 'Dismissed by user':
                    dialog = Adw.AlertDialog.new(
                        'Could not open file', err.message
                    )
                    dialog.add_response('ok', 'Ok')
                    dialog.set_default_response('ok')
                    dialog.set_close_response('ok')
                    dialog.choose(self, None, None)
                return

            # - Launch the file-based capture in another task
            # - Switch the trigger button to a "Stop capture" button
            #   (with dangerous/red styling?) when a capture to
            #   a PCAP file is active

            def do_open(*args):
                file_path = open_result.get_path()

                visible_file_path = file_path
                if visible_file_path.startswith(
                    '/run/user'
                ):  # Flatpak-sandboxed path
                    visible_file_path = visible_file_path.split('/').pop()

                self.pcap_capture_row.set_subtitle(
                    'Writing to: ' + visible_file_path
                )

                self.create_pcap_pipe(open_result)

            if self.input_obj.state != InputState.Closed:
                # Enable network-related logs, if this is a live device

                self.log_manager.register_ota_related_logs(do_open)

                self.pick_pcap_file_button.set_visible(False)
                self.stop_pcap_capture_button.set_visible(True)
                self.pcap_capture_row.set_activatable_widget(
                    self.stop_pcap_capture_button
                )
            else:
                # Just spawn Wireshark if this is a DLF file

                do_open()

        file_picker = Gtk.FileDialog()
        file_picker.set_initial_name('output_file.pcap')
        file_picker.save(self, callback=file_picked)

    @Gtk.Template.Callback()
    def stop_pcap_capture_clicked(self, target: Gtk.Button, *args):
        if self.output_pcap:
            self.output_pcap.close()
            self.output_pcap = None

    def create_pcap_pipe(self, output_file: Gio.File):
        assert not self.output_pcap

        self.output_pcap = PcapOutput(
            mode_selector=InteractiveGUIFileOutModeSelector(output_file, self),
            output_file=output_file,
        )

        def on_stream_closed(*args):
            self.pick_pcap_file_button.set_visible(True)
            self.stop_pcap_capture_button.set_visible(False)
            self.pcap_capture_row.set_activatable_widget(
                self.pick_pcap_file_button
            )
            self.pcap_capture_row.set_subtitle(None)

        def on_stream_available(*args):
            # Transmit on-the-fly converted ota rrc gsmtap v3 pcap -
            #   use adapter classes for data conversion
            OTADecoder(self.output_pcap, self.input_obj)

            def close_wireshark(*args):
                if self.output_pcap:
                    self.output_pcap.close()
                    self.output_pcap = None

            self.input_obj.closed.connect(close_wireshark)

            # If this is a DLF file, process data
            self.input_obj.process_stream()

        self.output_pcap.stream_closed.connect(on_stream_closed)

        self.output_pcap.stream_active.connect(on_stream_available)
        self.output_pcap.open_stream()
        # ⚠️ WIP

    def create_wireshark_pipe(self):
        assert not self.wireshark_instance

        self.wireshark_instance = PcapOutput(use_wireshark=True)

        def on_stream_closed(*args):
            self.start_ws_capture_button.set_visible(True)
            self.stop_ws_capture_button.set_visible(False)
            self.ws_capture_row.set_activatable_widget(
                self.start_ws_capture_button
            )

        def on_stream_available(*args):
            # Transmit on-the-fly converted ota rrc gsmtap v3 pcap -
            #   use adapter classes for data conversion
            OTADecoder(self.wireshark_instance, self.input_obj)

            def close_wireshark(*args):
                if self.wireshark_instance:
                    self.wireshark_instance.close()
                    self.wireshark_instance = None

            self.input_obj.closed.connect(close_wireshark)

            # If this is a DLF file, process data
            self.input_obj.process_stream()

        self.wireshark_instance.stream_closed.connect(on_stream_closed)

        self.wireshark_instance.stream_active.connect(on_stream_available)
        self.wireshark_instance.open_stream()
        # ⚠️ WIP

    def on_title_change(self, *args):
        self.set_title(self.input_obj.full_name)

    def on_state_change(self, *args):
        if not isinstance(self.input_obj, DLFInput):
            self.qcdm_stack.set_sensitive(
                self.input_obj.state == InputState.Processing
            )

        self.parent.update_serial_modems()

    def on_quit(self, *args):
        self.input_obj.close()

        if self.plugin_watch_task:
            self.plugin_watch_task.cancel()
            self.plugin_watch_task = None

    def get_log_support_info(self):
        def req_cb(
            response: DiagResponse,
        ):  # , log_mask: Optional[FullLogMask]
            pass
            self.input_obj.state = InputState.Processing
            # ⚠️ TODO ➡️ Add due error HANDLING Here?

        self.log_manager.get_supported_log_ranges(req_cb)

    def disable_logs(self):
        def req_cb(response: DiagResponse):
            pass
            self.get_log_support_info()
            # ⚠️ TODO ➡️ Add due error HANDLING Here?

        self.log_manager.disable_logs(req_cb)

    def gather_wireshark_info(self):
        def on_version(version: Optional[str]):
            if not version:
                self.wireshark_version_label.set_text('(Unavailable ⚠️)')
                # (⚠️ Maybe display/add extra download instructions?)
            else:
                self.wireshark_version_label.set_text(version)

        PcapOutput.check_wireshark_version(on_version)

    def gather_device_info(self):
        # Use self.input_obj to display Diag-related
        # info in the first tab of QCDMWindow
        #
        # For this, send a write command to the DBus
        # daemon

        payload = DiagVernoFReq()
        payload._check()

        diag_request = DiagRequest()
        diag_request.cmd_code = DiagCmd.verno_f
        diag_request.payload = payload
        diag_request._check()

        def req_cb(response: DiagResponse):
            info('DiagResponse received for DiagCmd.verno_f: %r' % response)

            # ⚠️ TODO ➡️ Add due error HANDLING Here?

            pretty_info = pretty_print_struct(response)
            self.device_info_buffer.set_text(pretty_info)

            # => Next step:
            #   Clear all logs before getting log support info

            self.disable_logs()

        self.input_obj.send_recv(
            diag_request, req_cb, accept_error=True, retry=True, retry_delay=2
        )
