#!/usr/bin/env python3

# Register resources
import diagng.utils.gresources

from diagng.protocol.qualcomm.modules.log_manager import (
    LogManager,
    FullLogMask,
)
from diagng.protocol.qualcomm.acquisition.base_input import (
    BaseQCDMInput,
    InputState,
)
from diagng.protocol.qualcomm.struct.diag_verno_f_req import DiagVernoFReq
from diagng.protocol.qualcomm.struct.diag_response import DiagResponse
from diagng.protocol.qualcomm.struct.diag_cmd_code import DiagCmdCode
from diagng.protocol.qualcomm.struct.diag_request import DiagRequest
from diagng.utils.kaitai_pretty_print import pretty_print_struct

from typing import Optional
from logging import info

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, Gio

DiagCmd = DiagCmdCode.DiagCmd


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/qcdm_window/window-autogenerated.ui'
)
class QCDMWindow(Adw.Window):
    __gtype_name__ = 'QCDMWindow'

    input_obj: BaseQCDMInput
    log_manager: LogManager
    parent: Adw.ApplicationWindow
    qcdm_stack: Adw.ViewStack = Gtk.Template.Child()
    device_info_buffer: Gtk.TextBuffer = Gtk.Template.Child()

    def __init__(
        self, parent: Adw.ApplicationWindow, input_obj: BaseQCDMInput
    ):
        super().__init__()

        self.input_obj = input_obj
        self.parent = parent

        self.log_manager = LogManager(input_obj)

        # ==> TODO ⚠️ initialize logging when buttons
        # in the PCAP tab are clicked

        self.set_transient_for(parent)
        self.set_title(self.input_obj.full_name)
        self.input_obj.connect('notify::full-name', self.on_title_change)
        self.input_obj.connect('notify::state', self.on_state_change)
        self.present()

        self.on_state_change()
        self.gather_device_info()

        self.connect('close-request', self.on_quit)

    @Gtk.Template.Callback()
    def start_capture_clicked(self, target: Gtk.Button, *args):
        # target.set_sensitive(False)
        print('⚠️ TODO: Start network capture here')

        # WRITE STEPS

        # (0. RESET LOGS AT APPLICATION STARTUP? BELOW ⬇️ ⬇️)

        # (1. ENABLE NETWORK-RELATED LOGS)

        # (2. SPAWN WIRESHARK PIPE, WITH FLATPAK-SPAWN IF NEEDED)

        # (3. TRANSMIT ON-THE-FLY CONVERTED OTA RRC GSMTAP v3 PCAP -
        #  USE ADAPTER CLASSES FOR DATA CONVERSION)

    def on_title_change(self, *args):
        self.set_title(self.input_obj.full_name)

    def on_state_change(self, *args):
        self.qcdm_stack.set_sensitive(
            self.input_obj.state == InputState.Processing
        )

        self.parent.update_serial_modems()

    def on_quit(self, *args):
        self.input_obj.close()

    def get_log_support_info(self):
        def req_cb(response: DiagResponse, log_mask: Optional[FullLogMask]):
            pass
            self.input_obj.state = InputState.Processing
            # ⚠️ TODO ➡️ Add due error HANDLING Here?

        self.log_manager.get_supported_log_ranges(req_cb)

    def gather_device_info(self):
        # Use self.input_obj to display Diag-related
        # info in the first tab of QCDMWindow
        #
        # For this, send a write command to the DBus
        # daemon

        payload = DiagVernoFReq()
        payload._check()

        diag_request = DiagRequest()
        diag_request.cmd_code = DiagCmd.verno_f
        diag_request.payload = payload
        diag_request._check()

        def req_cb(response: DiagResponse):
            info('DiagResponse received for DiagCmd.verno_f: %r' % response)

            # ⚠️ TODO ➡️ Add due error HANDLING Here?

            pretty_info = pretty_print_struct(response)
            self.device_info_buffer.set_text(pretty_info)

            # => ℹ️ Next step:
            # ⚠️ TODO: Clear all logs before getting log support info? (https://github.com/P1sec/DiagNG/issues/29)

            self.get_log_support_info()

        self.input_obj.send_recv(
            diag_request, req_cb, accept_error=True, retry=True, retry_delay=2
        )
