
[build-system]
requires = [
    # Build dependencies for own project (we
    # don't use uv_build as it is hard to
    # bundle into Flatpak)
    "setuptools>=69",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "diagng"
version = "0.1.0"
description = "Draft for DiagNG"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Telecommunications Industry",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: System :: Networking",
    "Topic :: Communications :: Telephony",
    "Topic :: Security",
    "Environment :: X11 Applications :: GTK",
    "Environment :: X11 Applications :: Gnome"
]
dependencies = [
    "crcmod>=1.7",
    "kaitaistruct>=0.11",
    "pygobject>=3.56.2",
    "pyudev>=0.24.4",
]

[project.scripts]
diagng = "diagng.ui.main_entry:main"
diagmond = "diagng.utils.spawn_diagmond:main"

[project.urls]
Homepage = "https://github.com/P1sec/DiagNG"
Repository = "https://github.com/P1sec/DiagNG"
Issues = "https://github.com/P1sec/DiagNG/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"diagng.ui.assets" = [
    "diagng.gresource"
]
"diagng.ui.assets.share.metainfo" = [
    "com.p1security.diagng.metainfo.xml"
]
"diagng.ui.assets.share.applications" = [
    "com.p1security.diagng.desktop"
]
"diagng.ui.assets.share.icons.scalable.apps" = [
    "com.p1security.diagng.svg"
]

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

