
[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"

[project]
name = "diagng"
version = "0.1.0"
description = "Draft for DiagNG"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygobject>=3.56.3",
]

[project.scripts]
diagng = "diagng.common.main_entry:main"

[project.urls]
Homepage = "https://github.com/P1sec/diagng"
Repository = "https://github.com/P1sec/diagng"
Issues = "https://github.com/P1sec/diagng/issues"

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

