name: diagng # you probably want to 'snapcraft register <name>'
adopt-info: share
title: diagng
license: GPL-3.0+
base: core24 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.3'

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  diagng:
    command: bin/diagng
    desktop: usr/share/applications/com.p1security.diagng.desktop
    extensions: [kde-neon-6] # gnome
    plugs:
      - home
      - unity7
      - network
      - network-status
      - hardware-observe
      - diagng-usb-plug
      - diagng-serial-port
      - raw-usb
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/android:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

plugs:
  diagng-usb-plug:
    interface: custom-device
    custom-device: diagng-usb-device
  diagng-serial-port:
    interface: serial-port

slots:
  diagng-usb-slot:
    interface: custom-device
    custom-device: diagng-usb-device
    devices:
      - /dev/ttyUSB[0-9]*
      - /dev/ttyHS[0-9]*

parts:
  diagng:
    plugin: python
    source: .

    stage-packages:
      - libdrm-common
      - libproxy1v5
      - adb
      - wireshark

    after: [python-runtime]

  python-runtime:
    plugin: nil
    stage-packages:
      - python-gi-dev
      - libgirepository-2.0-dev
      - librsvg2-common
      - librsvg2-2
      - adwaita-icon-theme
      - gir1.2-jsonrpc-1.0
      - gir1.2-json-1.0
      - gir1.2-modemmanager-1.0
      - gir1.2-adw-1
      - gir1.2-gtksource-5

    override-prime: |
      snapcraftctl prime
      export GDK_PIXBUF_MODULEDIR=$(realpath usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/*/loaders)
      usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache

  share:
    plugin: dump
    source: src/diagng/ui/assets/
    parse-info: [com.p1security.diagng.metainfo.xml]
    source-type: local

    override-pull: |
      snapcraftctl pull

      rm -f *.ui *.blp *.cmb *.sh *.gresource*

      # Point icon to the correct location
      sed -i -e 's|Icon=com.p1security.diagng|Icon=/usr/share/icons/hicolor/scalable/apps/com.p1security.diagng.svg|g' com.p1security.diagng.desktop
      install -Dm644 com.p1security.diagng.metainfo.xml -t usr/share/metainfo/
      install -Dm644 com.p1security.diagng.desktop -t usr/share/applications/
      install -Dm644 com.p1security.diagng.svg -t usr/share/icons/hicolor/scalable/apps/

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
