#!/usr/bin/env python3
from diagng.system.adb.adb_scripts.info_gathering import InformationGathering
from diagng.system.adb.adb_scripts.enable_diag_usb import EnableDiagUsb
from diagng.system.adb.adb_scripts.base_script import BaseScript
from diagng.gobject.adb_device import ADBDevice

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, GObject, GLib

# Register resources
import diagng.utils.gresources


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/main_window/adb_device_row-autogenerated.ui'
)
class ADBDeviceRow(Adw.ExpanderRow):
    __gtype_name__ = 'ADBDeviceRow'

    is_online = GObject.Property(type=bool, default=False)

    device = GObject.Property(type=ADBDevice)
    info_gathering = GObject.Property(type=BaseScript)

    auto_diag_setup_row: Adw.ExpanderRow = Gtk.Template.Child()
    diag_port_active_row: Adw.ActionRow = Gtk.Template.Child()
    xiaomi_trick_row: Adw.ExpanderRow = Gtk.Template.Child()
    system_info_row: Adw.ExpanderRow = Gtk.Template.Child()
    enable_diag_usb_row: Adw.ExpanderRow = Gtk.Template.Child()
    enable_diag_usb_buffer: Gtk.TextBuffer = Gtk.Template.Child()
    system_info_buffer: Gtk.TextBuffer = Gtk.Template.Child()
    system_info_spinner: Adw.Spinner = Gtk.Template.Child()
    baseband_ril_row: Adw.ActionRow = Gtk.Template.Child()
    baseband_ril_label: Gtk.Label = Gtk.Template.Child()
    root_binary_label: Gtk.Label = Gtk.Template.Child()
    diag_device_label: Gtk.Label = Gtk.Template.Child()
    supported_arch_row: Adw.ActionRow = Gtk.Template.Child()
    supported_arch_label: Gtk.Label = Gtk.Template.Child()
    android_version_label: Gtk.Label = Gtk.Template.Child()
    current_usb_mode_label: Gtk.Label = Gtk.Template.Child()

    main_window: 'MainWindow'

    def __init__(self, dev=None, main_window=None):
        super().__init__()

        if dev:
            self.device = dev
            self.main_window = main_window

            self.device.connect('notify', self.on_device_update)
            self.on_device_update(self.device)

    def on_device_update(self, dev: ADBDevice, *args):
        self.set_title(
            '<b>%s</b> (transport id #%s, serial ID %s)'
            % (
                GLib.markup_escape_text(dev.model_name or '', -1),
                # ^ TODO gather extra info from UDev?
                GLib.markup_escape_text(dev.transport_id or '', -1),
                GLib.markup_escape_text(dev.serial_str or '', -1),
            )
        )
        self.set_subtitle(GLib.markup_escape_text(dev.text_summary or '', -1))

        is_online = dev.state == 'device'

        if is_online and not self.is_online:
            self.is_online = True

            self.info_gathering = InformationGathering(self.device)

            # ⚠️ TODO: Use the right model so that it works here 🪧 ⬅️ ⬅️ ⚠️
            self.info_gathering.bind_property(
                'read_keys_text', self.system_info_buffer, 'text'
            )

            def update_ig(*args):
                keys_dict = self.info_gathering.read_keys_dict

                android_version = keys_dict.get('ANDROID_VERSION')
                android_sdk = keys_dict.get('ANDROID_SDK')
                if android_version and android_sdk:
                    self.android_version_label.set_label(
                        f'Android {android_version} (SDK {android_sdk})'
                    )

                firmware_version = keys_dict.get('BUILD_INFO')
                firmware_date = keys_dict.get('BUILD_DATE')
                if firmware_version and firmware_date:
                    self.system_info_row.set_subtitle(
                        f'{firmware_version} - Released {firmware_date}'
                    )

                abi_list = keys_dict.get('CPU_ABILIST')
                if abi_list:
                    self.supported_arch_label.set_label(
                        abi_list.replace(',', ' + ')
                    )

                # kernel_version = keys_dict.get('KERNEL')
                # if kernel_version:
                #     self.supported_arch_row.set_subtitle(kernel_version)

                ril_name = keys_dict.get('BASEBAND_RIL')
                if ril_name:
                    self.baseband_ril_label.set_label(ril_name)
                    self.system_info_spinner.set_visible(False)

                ril_version = keys_dict.get('BASEBAND_VERSION')
                if ril_version:
                    self.baseband_ril_row.set_subtitle(
                        'Version ' + ','.join(set(ril_version.split(',')))
                    )

                su_path = keys_dict.get('SU_PATH')
                if su_path:
                    if su_path != 'NOT_FOUND':
                        self.root_binary_label.set_label('Found at ' + su_path)

                        self.enable_diag_usb_row.set_visible(
                            'diag' not in keys_dict.get('USB_CONFIG', '')
                        )
                    else:
                        self.root_binary_label.set_label(
                            '(No "su" binary detected, is your phone rooted?)'
                        )

                self.auto_diag_setup_row.set_visible(
                    'diag' not in keys_dict.get('USB_CONFIG', '')
                )
                self.diag_port_active_row.set_visible(
                    'diag' in keys_dict.get('USB_CONFIG', '')
                )

                self.xiaomi_trick_row.set_visible(
                    'diag' not in keys_dict.get('USB_CONFIG', '')
                    and 'xiaomi' in keys_dict.get('BRAND', '').lower()
                )

                usb_mode = keys_dict.get('USB_CONFIG')
                if usb_mode:
                    self.current_usb_mode_label.set_label(usb_mode)

                if keys_dict.get('DIAG_EXISTS') == 'Y':
                    diag_text = '/dev/diag found'
                elif keys_dict.get('FFS_DIAG_EXISTS') == 'Y':
                    if usb_mode and 'diag' in usb_mode:
                        diag_text = '/dev/ffs-diag found'
                    else:
                        diag_text = (
                            '/dev/ffs-diag found, please change the USB mode'
                        )
                elif keys_dict.get('DEV_READABLE') == 'N':
                    diag_text = "/dev can't be read in non-root mode"
                else:
                    diag_text = 'No /dev/diag device found, this baseband may be unsupported'
                self.diag_device_label.set_label(diag_text)

            self.info_gathering.connect('notify::read-keys-dict', update_ig)
            self.info_gathering.launch()

    @Gtk.Template.Callback()
    def trigger_usb_switch(self, *args):
        script = EnableDiagUsb(self.device)

        def diag_enabled(*args):
            self.enable_diag_usb_row.set_enable_expansion(True)
            self.enable_diag_usb_row.set_expanded(True)
            self.enable_diag_usb_buffer.set_text(script.text_output)

        script.finished.connect(diag_enabled)
        script.launch()

    @Gtk.Template.Callback()
    def trigger_auto_diag_setup(self, *args):
        dialog = Adw.AlertDialog.new(
            'Not implemented yet',
        )
        dialog.add_response('ok', 'Ok')
        dialog.set_default_response('ok')
        dialog.set_close_response('ok')
        dialog.choose(self.main_window, None, None)

    # TODO set a "suggested_action" object
    # attribute pointing to a given script
    # depending on the phone and vendor
    # model? e.g launch privileged
    # APK on xiaomi, send dial code
    # on Samsung, etc.

    """
    def confirm_callback(
        alert_dialog: Adw.AlertDialog, result: Gio.AsyncResult
    ):

        if alert_dialog.choose_finish(result) == 'yes':


            dialog = Adw.AlertDialog.new(
                "XX QUESTION",
            )
            dialog.add_response('yes', 'Yes')
            dialog.add_response('no', 'No')
            dialog.set_default_response('yes')
            dialog.set_close_response('no')
            dialog.choose(self.main_window, None, confirm_callback)
    """
