#!/usr/bin/env python3
from diagng.system.adb.adb_scripts.qcdm_enable_xiaomi import QCDMEnableXiaomi
from diagng.gobject.adb_device import ADBDevice

from logging import debug

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, GObject, GLib

# Register resources
import diagng.utils.gresources


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/main_window/mi_apk_chooser-autogenerated.ui'
)
class APKSelectWindow(Adw.Dialog):
    __gtype_name__ = 'APKSelectWindow'

    parent: 'DeviceRow'

    def __init__(self, parent: 'DeviceRow'):
        super().__init__()

        self.parent = parent

    @Gtk.Template.Callback()
    def on_select_button(self, *args):
        debug('⚠️ WIP on_select_button')

    @Gtk.Template.Callback()
    def on_cancel_button(self, *args):
        debug('⚠️ WIP on_cancel_button')
