#!/usr/bin/env python3
from diagng.system.adb.adb_scripts.qcdm_enable_xiaomi import QCDMEnableXiaomi
from diagng.gobject.adb_device import ADBDevice

from logging import debug

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, GLib, Gio

# Register resources
import diagng.utils.gresources


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/main_window/mi_apk_chooser-autogenerated.ui'
)
class APKSelectWindow(Adw.Dialog):
    __gtype_name__ = 'APKSelectWindow'

    parent: 'DeviceRow'
    file_dialog: Gtk.FileDialog = Gtk.Template.Child()
    file_error_dialog: Adw.AlertDialog = Gtk.Template.Child()

    def __init__(self, parent: 'DeviceRow'):
        super().__init__()

        self.parent = parent
        self.file_error_dialog.add_response('ok', 'Ok')

    def on_open(self, obj: Gtk.FileDialog, res: Gio.AsyncResult):
        try:
            open_file: Gio.File = obj.open_finish(res)
            data: bytes = open_file.load_contents(None)[1]
        except GLib.GError as err:
            if err.message != 'Dismissed by user':
                self.file_error_dialog.set_body(err.message)
                self.file_error_dialog.choose(self, None, None)
        else:
            debug('⚠️ WIP on_open')

    @Gtk.Template.Callback()
    def on_select_button(self, *args):
        self.file_dialog.open(self.parent.main_window, None, self.on_open)

    @Gtk.Template.Callback()
    def on_cancel_button(self, *args):
        self.close()
