#!/usr/bin/env python3
from diagng.system.adb.adb_scripts.qcdm_enable_xiaomi import QCDMEnableXiaomi

from logging import debug
from hashlib import sha1

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, GLib, Gio

# Register resources
import diagng.utils.gresources


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/main_window/mi_apk_chooser-autogenerated.ui'
)
class APKSelectWindow(Adw.Dialog):
    __gtype_name__ = 'APKSelectWindow'

    parent: 'DeviceRow'
    file_dialog: Gtk.FileDialog = Gtk.Template.Child()
    file_error_dialog: Adw.AlertDialog = Gtk.Template.Child()
    file_checksum_dialog: Adw.AlertDialog = Gtk.Template.Child()
    subprocess_info_text: Gtk.Label = Gtk.Template.Child()

    KNOWN_CHECKSUMS = [
        '3a584b8cecb45380d74f6e9a4e1e2bef523ab462',
        '45c6314f176a760d3735ab031b3f29e9c47c94b8',
    ]

    def __init__(self, parent: 'DeviceRow'):
        super().__init__()

        self.parent = parent

        self.file_error_dialog.add_response('ok', 'Ok')

        self.file_checksum_dialog.add_response('continue', 'Continue')
        self.file_checksum_dialog.add_response('cancel', 'Cancel')

    def on_open(self, obj: Gtk.FileDialog, res: Gio.AsyncResult):
        try:
            open_file: Gio.File = obj.open_finish(res)
            data: bytes = open_file.load_contents(None)[1]
        except GLib.GError as err:
            if err.message != 'Dismissed by user':
                self.file_error_dialog.set_body(err.message)
                self.file_error_dialog.choose(self, None, None)
        else:
            # Validate checksum or display a confirm dialog

            known_file = sha1(data).hexdigest() in self.KNOWN_CHECKSUMS

            if not known_file:

                def on_confirm(
                    alert_dialog: Adw.AlertDialog, result: Gio.AsyncResult
                ):

                    if alert_dialog.choose_finish(result) == 'continue':
                        self.launch_diag_task(open_file, data)

                self.file_checksum_dialog.choose(self, None, on_confirm)

            else:
                # Launch the "QCDMEnableXiaomi" task

                self.launch_diag_task(open_file, data)

    def launch_diag_task(self, apk_file: Gio.File, apk_bytes: bytes):
        self.close()

        script = QCDMEnableXiaomi(self.parent.device, apk_bytes)

        def diag_enabled(*args):
            self.parent.xiaomi_trick_row.set_enable_expansion(True)
            self.parent.xiaomi_trick_row.set_expanded(True)
            self.parent.xiaomi_trick_buffer.set_text(script.text_output)

        script.finished.connect(diag_enabled)
        script.launch()

    @Gtk.Template.Callback()
    def on_select_button(self, *args):
        self.file_dialog.open(self.parent.main_window, None, self.on_open)

    @Gtk.Template.Callback()
    def on_cancel_button(self, *args):
        self.close()
