name: diagng # you probably want to 'snapcraft register <name>'
adopt-info: share
title: diagng
license: GPL-3.0+
base: core24 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.3'

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  diagng:
    command: bin/diagng
    desktop: usr/share/applications/com.p1security.diagng.desktop
    # We need to use the kde-neon-6 extension
    # rather than the gnome one in order to
    # have Wireshark to be spawnable
    extensions: [kde-neon-6]
    plugs:
      - home
      - unity7
      - network
      - network-status
      - hardware-observe
      - diagng-usb-plug
      - diagng-serial-port
      - raw-usb
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/android:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  diagng-usb-plug:
    interface: custom-device
    custom-device: diagng-usb-device
  diagng-serial-port:
    interface: serial-port

slots:
  diagng-usb-slot:
    interface: custom-device
    custom-device: diagng-usb-device
    devices:
      - /dev/ttyUSB[0-9]*
      - /dev/ttyHS[0-9]*

parts:
  diagng:
    plugin: python
    source: .

    stage-packages:
      - libdrm-common
      - libproxy1v5
      - adb
      - wireshark

    after: [python-runtime]

  python-runtime:
    plugin: nil
    stage-packages:
      - python-gi-dev
      - libgirepository-2.0-dev
      - librsvg2-common
      - librsvg2-2
      - gir1.2-modemmanager-1.0
      - gir1.2-adw-1
      - gir1.2-gtksource-5

  share:
    plugin: dump
    source: src/diagng/ui/assets/share/
    parse-info: [com.p1security.diagng.metainfo.xml]
    source-type: local

    override-pull: |
      snapcraftctl pull

      sed -i -e 's|Icon=com.p1security.diagng|Icon=/usr/share/icons/hicolor/scalable/apps/com.p1security.diagng.svg|g' share/applications/com.p1security.diagng.desktop
      mkdir -p usr
      mv share usr
      chmod -R 644 usr/share

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy
  # The kde-neon-6 Snap extension includes a build of GDK Pixbuf but
  # doesn't include the librsvg2-common package that provides the
  # SVG loader for GDK Pixbuf, hence if we don't include this
  # loader ourverselves and regenerate the GDK Pixbuf loaders
  # cache after that the icons won't show up in our GTK-4 app.
  $SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
