#!/usr/bin/env python3
from typing import List, Dict, Tuple, Optional, Union
from logging import info, error, debug
from collections import defaultdict
from traceback import format_exc
from json import loads

# Register resources
import diagng.utils.gresources

from diagng.ui.main_window.models.usb_interfaces import create_usb_interfaces
from diagng.utils.spawn_diagmond import spawn_diagmond_as_outer_process
from diagng.ui.main_window.models.adb_devices import create_adb_device
from diagng.ui.main_window.models.spi_modems import create_spi_modem
from diagng.ui.main_window.models.mm_modems import create_mm_modem
from diagng.ui.authorization_dialog.imp import AuthorizationDialog
from diagng.utils.usb_port_detecter import detect_diag_usb_ports
from diagng.protocol.qualcomm.acquisition import spi_input
from diagng.protocol.qualcomm.acquisition import usb_input
from diagng.gobject.usb_interface import USBInterface
from diagng.gobject.mm_modem import ModemManagerModem
from diagng.gobject.serial_modem import SerialModem
from diagng.gobject.mm_port import ModemManagerPort
from diagng.gobject.serial_port import SerialPort
from diagng.gobject.usb_device import USBDevice

# Based on https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#ui-from-graphical-designer

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
gi.require_version('GtkSource', '5')
from gi.repository import Gtk, Adw, Gdk, GLib, Gio, GObject, GtkSource


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/main_window/window-autogenerated.ui'
)
class MainWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'

    app: 'MainApplication'
    adw_style_manager: Adw.StyleManager

    auth_dialog_showed: bool = False

    # All tabs - banner

    mm_link_banner: Adw.ActionRow = Gtk.Template.Child()
    usb_link_banner: Adw.ActionRow = Gtk.Template.Child()
    spi_link_banner: Adw.ActionRow = Gtk.Template.Child()
    adb_link_banner: Adw.ActionRow = Gtk.Template.Child()

    # UI panel: USB

    run_diagmond_popover: Adw.PreferencesGroup = Gtk.Template.Child()

    usb_interfaces_group: Gtk.SingleSelection = Gtk.Template.Child()
    usb_devices: Gio.ListStore  # Of USBDevice items

    nusb_selection: Gtk.SingleSelection = Gtk.Template.Child()

    usb_selection: Gtk.SingleSelection = Gtk.Template.Child()

    udev_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    udev_debug_view: GtkSource.View
    udev_sourceview_buffer: GtkSource.Buffer

    nusb_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    nusb_debug_view: GtkSource.View
    nusb_sourceview_buffer: GtkSource.Buffer

    # UI panel: SPI

    serial_modems: Gio.ListStore  # Of SerialPort items
    spi_ports_group: Adw.PreferencesGroup = Gtk.Template.Child()

    spi_selection: Gtk.SingleSelection = Gtk.Template.Child()

    tokio_serial_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    tokio_serial_debug_view: GtkSource.View
    tokio_serial_sourceview_buffer: GtkSource.Buffer

    # UI panel: ADB

    adb_status_row: Adw.ActionRow = Gtk.Template.Child()
    adb_status_label: Gtk.Label = Gtk.Template.Child()
    adb_daemon_missing: Gtk.Label = Gtk.Template.Child()

    adb_devices_group: Adw.PreferencesGroup = Gtk.Template.Child()

    # UI panel: ModemManager

    mm_status_row: Adw.ActionRow = Gtk.Template.Child()
    mm_status_label: Gtk.Label = Gtk.Template.Child()
    mm_version_row: Adw.ActionRow = Gtk.Template.Child()
    mm_version_label: Gtk.Label = Gtk.Template.Child()

    detected_modems_group: Adw.PreferencesGroup = Gtk.Template.Child()

    mm_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    mm_debug_view: GtkSource
    mm_sourceview_buffer: GtkSource.Buffer

    # UI panel: UDev

    udev_rules_selection: Gtk.SingleSelection = Gtk.Template.Child()

    def __init__(self, app):
        super().__init__()

        self.app = app
        self.set_application(app)

        # Perform data bindings

        self.bind_data()

        # Connect actions

        self.connect_actions()

        # Connect signals

        self.connect_signals()

        # Reset the default UI state

        self.reset_state()

    @Gtk.Template.Callback()
    def launch_diagmond(self, target: Gtk.Button, *args):
        target.set_sensitive(False)
        spawn_diagmond_as_outer_process()

    def bind_data(self):

        lang_manager = GtkSource.LanguageManager.new()

        # Build USB device tree views, for the nusb
        # and UDev data sources

        self.nusb_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.diagmond_communicator.nusb_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        self.usb_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.device_scanner.usb_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        # Build nusb debug SourceView

        self.nusb_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.nusb_debug_view = GtkSource.View.new_with_buffer(
            self.nusb_sourceview_buffer
        )
        self.nusb_debug_view.set_editable(False)
        self.nusb_debug_viewport.set_child(self.nusb_debug_view)

        # Build UDev devices debug SourceView

        self.udev_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.udev_debug_view = GtkSource.View.new_with_buffer(
            self.udev_sourceview_buffer
        )
        self.udev_debug_view.set_editable(False)
        self.udev_debug_viewport.set_child(self.udev_debug_view)

        # Build serial models list (depends on both
        # UDev serial ports and ModemManager modems)

        self.serial_modems = Gio.ListStore.new(SerialModem)

        self.spi_ports_group.bind_model(
            self.serial_modems, create_spi_modem, self
        )

        # Build SPI device tree view

        self.spi_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.device_scanner.spi_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        # Build tokio-serial debug SourceView

        self.tokio_serial_sourceview_buffer = (
            GtkSource.Buffer.new_with_language(
                lang_manager.get_language('json')
            )
        )

        self.tokio_serial_debug_view = GtkSource.View.new_with_buffer(
            self.tokio_serial_sourceview_buffer
        )
        self.tokio_serial_debug_view.set_editable(False)
        self.tokio_serial_debug_viewport.set_child(
            self.tokio_serial_debug_view
        )

        # Build ADB devices list

        def got_version(*args):
            self.adb_status_row.set_subtitle(
                'Protocol version %d' % self.app.adb_watcher.version
                if self.app.adb_watcher.version
                else ''
            )

        self.app.adb_watcher.connect('notify::version', got_version)
        got_version()

        def got_connect_status(*args):
            self.adb_status_label.set_label(
                'Connected'
                if self.app.adb_watcher.is_connected
                else 'Disconnected'
            )

        self.app.adb_watcher.connect(
            'notify::is-connected', got_connect_status
        )
        got_connect_status()

        self.app.adb_watcher.bind_property(
            'is-failed', self.adb_daemon_missing, 'visible'
        )

        self.adb_devices_group.bind_model(
            self.app.adb_watcher.devices, create_adb_device, self
        )

        # Bind ModemManager modem list

        self.detected_modems_group.bind_model(
            self.app.modem_manager.mm_instance.modems, create_mm_modem
        )

        # Build ModemManager debug SourceView

        self.mm_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.mm_debug_view = GtkSource.View.new_with_buffer(
            self.mm_sourceview_buffer
        )
        self.mm_debug_view.set_editable(False)
        self.mm_debug_viewport.set_child(self.mm_debug_view)

        # Build USB interfaces list (depends on both
        # nusb raw descriptors and UDev device specs)

        self.usb_devices = Gio.ListStore.new(USBDevice)

        self.usb_interfaces_group.bind_model(
            self.usb_devices, create_usb_interfaces, self
        )

        # Build UDev rules list

        self.udev_rules_selection.set_model(
            self.app.diagmond_communicator.udev_rules_model
        )

        # Monitor for dark mode changes

        self.adw_style_manager = Adw.StyleManager.get_default()
        self.sync_sourceview_theme()
        self.adw_style_manager.connect('notify', self.sync_sourceview_theme)

    def add_simple_action(
        self, name, callback, param_type: Optional[GLib.VariantType] = None
    ):

        action = Gio.SimpleAction.new(name, param_type)
        action.connect('activate', callback)
        self.add_action(action)

    def connect_actions(self):

        def copy_nusb_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.nusb_debug_data)

        self.add_simple_action('copy-nusb-debug-info', copy_nusb_debug_info)

        def copy_udev_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.udev_debug_data)

        self.add_simple_action('copy-udev-debug-info', copy_udev_debug_info)

        def copy_tokio_serial_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.tokio_serial_debug_data)

        self.add_simple_action(
            'copy-tokio-serial-debug-info', copy_tokio_serial_debug_info
        )

        def copy_mm_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.mm_debug_data)

        self.add_simple_action('copy-mm-debug-info', copy_mm_debug_info)

    def connect_signals(self):

        # Application exit

        # self.connect('close-request', self.on_quit)
        self.app.connect('shutdown', self.on_quit)

        # All tabs - banner

        self.app.modem_manager.mm_instance.connect(
            'notify::is-running', self.update_daemon_statuses
        )
        self.app.diagmond_communicator.connect(
            'notify::bus-connected', self.update_daemon_statuses
        )

        # USB tab

        self.app.modem_manager.mm_instance.modems.connect(
            'items-changed', self.update_usb_devices
        )
        self.app.connect('notify::nusb-debug-data', self.update_usb_devices)
        self.app.connect('notify::udev-debug-data', self.update_usb_devices)

        self.app.connect(
            'notify::udev-debug-data', self.update_udev_debug_data
        )
        self.app.connect(
            'notify::nusb-debug-data', self.update_nusb_debug_data
        )

        # SPI tab

        self.app.device_scanner.spi_devices.connect(
            'items-changed', self.update_serial_modems
        )
        self.app.modem_manager.mm_instance.modems.connect(
            'items-changed', self.update_serial_modems
        )

        self.app.connect(
            'notify::tokio-serial-debug-data',
            self.update_tokio_serial_debug_data,
        )

        # ModemMananger status

        self.app.modem_manager.mm_instance.connect(
            'notify', self.update_mm_instance
        )

        self.app.connect('notify::mm-debug-data', self.update_mm_debug_data)

        self.app.modem_manager.mm_instance.modems.connect(
            'items-changed', self.update_mm_modems
        )

    def reset_state(self):
        # All tabs - banner

        self.update_daemon_statuses()

        # USB tab

        self.update_usb_devices()
        self.update_nusb_debug_data()
        self.update_udev_debug_data()

        # SPI tab

        self.update_serial_modems()
        self.update_tokio_serial_debug_data()

        # ModemManager tab

        self.mm_status_row.set_subtitle('Fetching information...')
        self.mm_status_label.set_label('')
        self.mm_version_label.set_label('')

        self.update_mm_modems()
        self.update_mm_instance()
        self.update_mm_debug_data()

    def update_daemon_statuses(self, *args):
        mm_running = self.app.modem_manager.mm_instance.is_running
        diagmond_running = self.app.diagmond_communicator.bus_connected
        # udev_reachable = True
        # adb_reachable = True

        if (
            not self.app.diagmond_communicator.proxy.get_name_owner()
            and not self.auth_dialog_showed
        ):
            self.auth_dialog_showed = True

            auth_dialog = AuthorizationDialog(self)
            auth_dialog.set_transient_for(self)
            auth_dialog.present()

        self.run_diagmond_popover.set_visible(not diagmond_running)

        self.usb_link_banner.set_title(
            'UDev status: REACHABLE - diagmond status: %s'
            % ('ON' if diagmond_running else 'OFF')
        )
        self.spi_link_banner.set_title(
            'UDev status: REACHABLE - diagmond status: %s'
            % ('ON' if diagmond_running else 'OFF')
        )
        self.mm_link_banner.set_title(
            'ModemManager Link: %s - diagmond status: %s'
            % (
                'ON' if mm_running else 'OFF',
                'ON' if diagmond_running else 'OFF',
            )
        )

    def sync_sourceview_theme(self, *args):
        is_dark_mode: bool = self.adw_style_manager.get_dark()

        color_scheme_manager = GtkSource.StyleSchemeManager.new()
        for scheme in color_scheme_manager.get_scheme_ids():
            is_dark_theme: bool = (
                'dark' in scheme or 'oblivion' in scheme or 'cobalt' in scheme
            )
            if is_dark_mode == is_dark_theme:
                self.udev_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.nusb_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.tokio_serial_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.mm_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                break

    def update_usb_devices(self, *args):
        detect_diag_usb_ports(
            loads(self.app.udev_debug_data or 'null'),
            loads(self.app.nusb_debug_data or 'null'),
            self.usb_devices,
            self.app.modem_manager.mm_instance.modems,
        )

    def update_nusb_debug_data(self, *args):
        if self.app.nusb_debug_data:
            self.nusb_debug_view.get_buffer().set_text(
                self.app.nusb_debug_data
            )

    def update_udev_debug_data(self, *args):
        if self.app.udev_debug_data:
            self.udev_debug_view.get_buffer().set_text(
                self.app.udev_debug_data
            )

    def update_tokio_serial_debug_data(self, *args):
        if self.app.tokio_serial_debug_data:
            self.tokio_serial_debug_view.get_buffer().set_text(
                self.app.tokio_serial_debug_data
            )

    def update_serial_modems(self, *args):

        self.spi_ports_group.set_visible(
            bool(self.app.device_scanner.spi_devices.get_n_items())
        )

        vid_pid_to_obj: Dict[str, SerialModem] = defaultdict(SerialModem)
        dev_path_to_mm_obj: Dict[
            str, Tuple[ModemManagerPort, ModemManagerModem]
        ] = {}

        for pos in range(
            self.app.modem_manager.mm_instance.modems.get_n_items()
        ):
            modem = self.app.modem_manager.mm_instance.modems.get_item(pos)

            for pos in range(modem.ports.get_n_items()):
                port = modem.ports.get_item(pos)

                dev_path_to_mm_obj[port.device_path] = (port, modem)

        for pos in range(self.app.device_scanner.spi_devices.get_n_items()):
            port: SerialPort = self.app.device_scanner.spi_devices.get_item(
                pos
            )

            modem: SerialModem = vid_pid_to_obj[port.usb_vid_pid]
            modem.usb_vid_pid = port.usb_vid_pid
            if not modem.ports.get_n_items():
                modem.first_port = port
            modem.ports.append(port)

            if port.tty_device_path in dev_path_to_mm_obj:
                mm_port, mm_modem = dev_path_to_mm_obj[port.tty_device_path]
                modem.mm_obj = mm_modem
                port.mm_obj = mm_port

        with self.serial_modems.freeze_notify():
            self.serial_modems.remove_all()
            for obj in vid_pid_to_obj.values():
                self.serial_modems.append(obj)

    def update_mm_instance(self, *args):
        if self.app.modem_manager.mm_instance.initialized:
            self.mm_status_row.set_subtitle(
                ('PID %d' % self.app.modem_manager.mm_instance.pid)
                if self.app.modem_manager.mm_instance.is_running
                and self.app.modem_manager.mm_instance.pid
                else ''
            )
            self.mm_status_label.set_label(
                'Started'
                if self.app.modem_manager.mm_instance.is_running
                else 'Stopped'
            )
            self.mm_version_row.set_visible(
                self.app.modem_manager.mm_instance.is_running
            )
            self.mm_version_label.set_label(
                self.app.modem_manager.mm_instance.version
                if self.app.modem_manager.mm_instance.version
                else ''
            )

    def update_mm_debug_data(self, *args):
        if self.app.mm_debug_data:
            self.mm_debug_view.get_buffer().set_text(self.app.mm_debug_data)

    def on_quit(self, *args):
        if (
            self.app.diagmond_serialdevice_om
            and self.app.diagmond_serialdevice_om.om
        ):
            self.app.diagmond_serialdevice_om.remove_dangling_objects()

    def disconnect_usb_intf(
        self, target: Gtk.Button, usb_dev: USBDevice, usb_intf: USBInterface
    ):
        info('disconnect_usb_intf called on %s' % usb_intf.full_intf_id)

        if usb_intf.full_intf_id in usb_input._connected_ports:
            usb_input._connected_ports[usb_intf.full_intf_id].close()

    def connect_usb_intf(
        self, target: Gtk.Button, usb_dev: USBDevice, usb_intf: USBInterface
    ):
        info('connect_usb_intf called on %s' % usb_intf.full_intf_id)

        if self.app.diagmond_communicator.bus_connected:

            def port_opened(proxy, result: Union[str, Exception], user_data):
                usb_dev, usb_intf = user_data

                if isinstance(result, Exception):
                    dialog = Adw.AlertDialog.new(
                        '⚠️ Failed to open port', repr(result)
                    )
                    error('Failed to open port: ' + repr(result))

                    dialog.add_response('ok', 'Ok')
                    dialog.choose(self, None, None)

                    usb_intf.connected = False
                    self.update_usb_devices()
                else:
                    object_path = result
                    info('Got new SerialDevice object path: ' + object_path)

                    self.app.diagmond_serialdevice_om.create_qcdm_window_usb(
                        object_path, usb_dev, usb_intf
                    )

            usb_intf.connected = True

            if usb_intf.udev_tty_device_path:
                self.app.diagmond_communicator.proxy.OpenSerialPort(
                    '(ss)',
                    usb_intf.udev_tty_device_path,
                    usb_intf.udev_tty_kernel_name,
                    result_handler=port_opened,
                    user_data=(usb_dev, usb_intf),
                )
            else:
                self.app.diagmond_communicator.proxy.OpenUSBInterface(
                    '(sssayqqyyy)',
                    usb_intf.udev_tty_device_path or '',
                    usb_intf.udev_tty_kernel_name or '',
                    usb_dev.bus_id,
                    usb_dev.port_chain,
                    int(usb_dev.vid_pid.split(':')[0], 16),
                    int(usb_dev.vid_pid.split(':')[1], 16),
                    usb_intf.conf_num,
                    usb_intf.intf_num,
                    usb_intf.alt_setting_num,
                    result_handler=port_opened,
                    user_data=(usb_dev, usb_intf),
                )
        else:
            dialog = Adw.AlertDialog.new(
                "⚠️ diagmond not available, can't open interface", None
            )
            error("diagmond not available, can't open interface")
            dialog.add_response('ok', 'Ok')
            dialog.choose(self, None, None)

    def disconnect_spi_port(self, target: Gtk.Button, serial_port: SerialPort):
        info('disconnect_spi_port called on %s' % serial_port.tty_device_path)

        if serial_port.tty_device_path in spi_input._connected_ports:
            spi_input._connected_ports[serial_port.tty_device_path].close()

    def connect_spi_port(self, target: Gtk.Button, serial_port: SerialPort):
        info('connect_spi_port called on %s' % serial_port.tty_device_path)

        if self.app.diagmond_communicator.bus_connected:

            def port_opened(proxy, result: Union[str, Exception], serial_port):
                if isinstance(result, Exception):
                    dialog = Adw.AlertDialog.new(
                        '⚠️ Failed to open port', repr(result)
                    )
                    error('Failed to open port: ' + repr(result))

                    dialog.add_response('ok', 'Ok')
                    dialog.choose(self, None, None)

                    serial_port.connected = False
                    self.update_serial_modems()
                else:
                    object_path = result
                    info('Got new SerialDevice object path: ' + object_path)

                    self.app.diagmond_serialdevice_om.create_qcdm_window_spi(
                        object_path, serial_port
                    )

            serial_port.connected = True
            self.update_serial_modems()

            self.app.diagmond_communicator.proxy.OpenSerialPort(
                '(ss)',
                serial_port.tty_device_path,
                serial_port.kernel_name,
                result_handler=port_opened,
                user_data=serial_port,
            )
        else:
            dialog = Adw.AlertDialog.new(
                "⚠️ diagmond not available, can't open port", None
            )
            error("diagmond not available, can't open port")
            dialog.add_response('ok', 'Ok')
            dialog.choose(self, None, None)

    def update_mm_modems(self, *args):

        self.detected_modems_group.set_visible(
            bool(self.app.modem_manager.mm_instance.modems.get_n_items())
        )
