#!/usr/bin/env python3
from os.path import dirname, realpath, exists, join
from os import stat, walk, scandir, access, W_OK
from subprocess import run
from shutil import which

from gi.repository import Gio

SCRIPT_DIR = dirname(realpath(__file__))
MODULE_DIR = dirname(realpath(SCRIPT_DIR))
ASSETS_DIR = realpath(join(MODULE_DIR, 'assets'))
RESOURCES_PATH = realpath(join(ASSETS_DIR, 'diagng.gresource'))


# Create a templated window object, in order
# to parse the Cambalache-produced UI file

if not exists(RESOURCES_PATH) or (
    access(RESOURCES_PATH, W_OK)
    and which('blueprint-compiler')
    and which('glib-compile-resources')
    and max(
        meta.stat().st_mtime
        for dir_name, _, _ in walk(ASSETS_DIR)
        for meta in scandir(dir_name)
    )
    > stat(RESOURCES_PATH).st_mtime
):
    for blueprint_name in [
        'udev_serial_tree_factory',
        'nusb_tree_factory',
        'diagng',
        'qcdm_window',
    ]:
        run(
            [
                'blueprint-compiler',
                'compile',
                '--output',
                blueprint_name + '-autogenerated.ui',
                blueprint_name + '.blp',
            ],
            cwd=ASSETS_DIR,
        )
    run(['glib-compile-resources', RESOURCES_PATH + '.xml'], cwd=ASSETS_DIR)

GIO_RESOURCES = Gio.Resource.load(RESOURCES_PATH)
Gio.resources_register(GIO_RESOURCES)
