#!/usr/bin/env python3

from diagng.utils.spawn_diagmond import spawn_diagmond_as_outer_process

# Register resources
import diagng.utils.gresources

from logging import info

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, Gio


@Gtk.Template(
    resource_path='/com/p1security/diagng/templates/authorization_dialog/window-autogenerated.ui'
)
class AuthorizationDialog(Adw.Window):
    __gtype_name__ = 'AuthorizationDialog'

    parent: 'MainWindow'

    do_launch: bool = False

    continue_button: Gtk.Button = Gtk.Template.Child()
    decline_button: Gtk.Button = Gtk.Template.Child()

    def __init__(self, parent: 'MainWindox'):
        super().__init__()

        self.continue_button.grab_focus()
        self.parent = parent

    @Gtk.Template.Callback()
    def on_decline(self, *args):
        if not self.do_launch:
            self.parent.destroy()

    @Gtk.Template.Callback()
    def on_continue(self, *args):
        self.do_launch = True
        spawn_diagmond_as_outer_process()
        self.close()
