#!/usr/bin/env python3

# Register resources
import diagng.utils.gresources

from diagng.parsing.struct.qualcomm.diag_verno_f_req import DiagVernoFReq
from diagng.parsing.struct.qualcomm.diag_response import DiagResponse
from diagng.parsing.struct.qualcomm.diag_cmd_code import DiagCmdCode
from diagng.parsing.struct.qualcomm.diag_request import DiagRequest
from diagng.acquisition.qualcomm.base_input import BaseQCDMInput
from diagng.utils.kaitai_pretty_print import pretty_print_struct

from logging import info

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, Gio

DiagCmd = DiagCmdCode.DiagCmd


@Gtk.Template(
    resource_path='/com/p1security/diagng/qcdm_window-autogenerated.ui'
)
class QCDMWindow(Adw.Window):
    __gtype_name__ = 'QCDMWindow'

    input_obj: BaseQCDMInput
    parent: Adw.ApplicationWindow
    device_info_buffer: Gtk.TextBuffer = Gtk.Template.Child()

    def __init__(
        self, parent: Adw.ApplicationWindow, input_obj: BaseQCDMInput
    ):
        super().__init__()

        self.input_obj = input_obj
        self.parent = parent

        self.set_transient_for(parent)
        self.set_title(self.input_obj.full_name)
        self.input_obj.connect('notify::full-name', self.on_title_change)
        self.present()

        self.gather_device_info()

        self.input_obj.connect('closed', self.on_input_closed)
        self.connect('close-request', self.on_quit)

    def on_title_change(self, *args):
        self.set_title(self.input_obj.full_name)

    def on_input_closed(self, *args):
        self.parent.update_serial_modems()

    def on_quit(self, *args):
        self.input_obj.close()

    def gather_device_info(self):
        # Use self.input_obj to display Diag-related
        # info in the first tab of QCDMWindow
        #
        # For this, send a write command to the DBus
        # daemon

        payload = DiagVernoFReq()
        payload._check()

        diag_request = DiagRequest()
        diag_request.cmd_code = DiagCmd.verno_f
        diag_request.payload = payload
        diag_request._check()

        def req_cb(response: DiagResponse):
            info('DiagResponse received for DiagCmd.verno_f: %r' % response)

            pretty_info = pretty_print_struct(response)
            self.device_info_buffer.set_text(pretty_info)

        self.input_obj.send_recv(diag_request, req_cb, accept_error=True)

        pass
