#!/usr/bin/env python3

# Register resources
import diagng.utils.gresources

from diagng.acquisition.qualcomm.base_input import BaseQCDMInput
from diagng.gobject.serial_port import SerialPort

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, Gio


@Gtk.Template(
    resource_path='/com/p1security/diagng/qcdm_window-autogenerated.ui'
)
class QCDMWindow(Adw.Window):
    __gtype_name__ = 'QCDMWindow'

    input_obj: BaseQCDMInput

    def __init__(
        self, parent: Adw.ApplicationWindow, input_obj: BaseQCDMInput
    ):
        super().__init__()

        self.input_obj = input_obj

        self.set_transient_for(parent)
        self.set_title(self.input_obj.full_name)
        self.present()

        self.gather_device_info()

    def gather_device_info(self):
        # WIP use self.dbus_serial_device to display
        # Diag-related info in the first tab of
        # QCDMWindow

        # = Spawn a GLib task reading (and logging?)
        # pseudo-HDLC events from the serial stream
        # (use nesting objects as adapters?)

        #   ===> Define a GObject INTERFACE with
        #    callback and signal-based connectivity
        #    in order to provide different adapters
        #    for different input sources (USB, ADB,
        #    SPI, DLF file, etc.) through
        #    subclassing?
        #        => Use Python metaclasses for
        #           abstracting?

        # + Send a write command to the DBus
        # daemon

        pass
