#!/usr/bin/env python3
from collections import defaultdict
from typing import List, Dict

# Register resources
import diagng.utils.gresources

from diagng.gobject.serial_port import SerialPort

# Based on https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#ui-from-graphical-designer

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
gi.require_version('GtkSource', '5')
from gi.repository import Gtk, Adw, GLib, Gio, GtkSource


@Gtk.Template(resource_path='/com/p1security/diagng/diagng-autogenerated.ui')
class MyWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'

    app: 'MainApplication'
    adw_style_manager: Adw.StyleManager

    # UI panel: ModemManager

    mm_link_banner: Adw.ActionRow = Gtk.Template.Child()
    usb_link_banner: Adw.ActionRow = Gtk.Template.Child()
    spi_link_banner: Adw.ActionRow = Gtk.Template.Child()
    adb_link_banner: Adw.ActionRow = Gtk.Template.Child()

    mm_status_row: Adw.ActionRow = Gtk.Template.Child()
    mm_status_label: Gtk.Label = Gtk.Template.Child()
    mm_version_row: Adw.ActionRow = Gtk.Template.Child()
    mm_version_label: Gtk.Label = Gtk.Template.Child()

    detected_modems_group: Adw.PreferencesGroup = Gtk.Template.Child()
    spi_ports_group: Adw.PreferencesGroup = Gtk.Template.Child()

    mm_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    mm_debug_view: GtkSource
    mm_sourceview_buffer: GtkSource.Buffer

    # UI panel: USB

    usb_selection: Gio.ListStore = Gtk.Template.Child()

    udev_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    udev_debug_view: GtkSource
    udev_sourceview_buffer: GtkSource.Buffer

    nusb_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    nusb_debug_view: GtkSource
    nusb_sourceview_buffer: GtkSource.Buffer

    # UI panel: SPI

    spi_selection: Gio.ListStore = Gtk.Template.Child()

    def __init__(self, app):
        super().__init__()

        self.app = app
        self.set_application(app)

        lang_manager = GtkSource.LanguageManager.new()

        # Build ModemManager debug SourceView

        self.mm_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.mm_debug_view = GtkSource.View.new_with_buffer(
            self.mm_sourceview_buffer
        )
        self.mm_debug_view.set_editable(False)
        self.mm_debug_viewport.set_child(self.mm_debug_view)

        # Build USB device tree view

        self.usb_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.device_scanner.usb_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        # Build SPI device tree view

        self.spi_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.device_scanner.spi_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        # Build UDev debug SourceView

        self.udev_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.udev_debug_view = GtkSource.View.new_with_buffer(
            self.udev_sourceview_buffer
        )
        self.udev_debug_view.set_editable(False)
        self.udev_debug_viewport.set_child(self.udev_debug_view)

        # Build nusb debug SourceView

        self.nusb_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.nusb_debug_view = GtkSource.View.new_with_buffer(
            self.nusb_sourceview_buffer
        )
        self.nusb_debug_view.set_editable(False)
        self.nusb_debug_viewport.set_child(self.nusb_debug_view)

        # Monitor for dark mode changes

        self.adw_style_manager = Adw.StyleManager.get_default()
        self.sync_sourceview_theme()
        self.adw_style_manager.connect('notify', self.sync_sourceview_theme)

        # Connect signals

        self.app.device_scanner.spi_devices.connect(
            'items-changed', self.update_spi_devices
        )
        self.app.modem_manager.mm_instance.modems.connect(
            'items-changed', self.update_mm_modems
        )
        self.app.modem_manager.mm_instance.connect(
            'notify::is-running', self.update_daemon_statuses
        )
        self.app.diagmond_communicator.connect(
            'notify::bus-connected', self.update_daemon_statuses
        )
        self.app.modem_manager.mm_instance.connect(
            'notify', self.update_mm_instance
        )
        self.app.connect('notify::mm-debug-data', self.update_mm_debug_data)
        self.app.connect(
            'notify::udev-debug-data', self.update_udev_debug_data
        )
        self.app.connect(
            'notify::nusb-debug-data', self.update_nusb_debug_data
        )

        # Reset the default UI state

        self.mm_status_row.set_subtitle('Fetching information...')
        self.mm_status_label.set_label('')
        self.mm_version_label.set_label('')

        self.update_daemon_statuses()
        self.update_spi_devices()
        self.update_mm_modems()
        self.update_mm_instance()
        self.update_mm_debug_data()
        self.update_udev_debug_data()
        self.update_nusb_debug_data()

    def update_daemon_statuses(self, *args):
        mm_running = self.app.modem_manager.mm_instance.is_running
        diagmond_running = self.app.diagmond_communicator.bus_connected
        # udev_reachable = True
        # adb_reachable = True

        self.mm_link_banner.set_title(
            'ModemManager Link: %s - diagmond status: %s'
            % (
                'ON' if mm_running else 'OFF',
                'ON' if diagmond_running else 'OFF',
            )
        )
        self.usb_link_banner.set_title(
            'UDev status: REACHABLE - diagmond status: %s'
            % ('ON' if diagmond_running else 'OFF')
        )
        self.spi_link_banner.set_title(
            'UDev status: REACHABLE - diagmond status: %s'
            % ('ON' if diagmond_running else 'OFF')
        )

    def sync_sourceview_theme(self, *args):
        is_dark_mode: bool = self.adw_style_manager.get_dark()

        color_scheme_manager = GtkSource.StyleSchemeManager.new()
        for scheme in color_scheme_manager.get_scheme_ids():
            is_dark_theme: bool = (
                'dark' in scheme or 'oblivion' in scheme or 'cobalt' in scheme
            )
            if is_dark_mode == is_dark_theme:
                self.mm_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.udev_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.nusb_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                break

    def update_mm_instance(self, *args):
        if self.app.modem_manager.mm_instance.initialized:
            self.mm_status_row.set_subtitle(
                ('PID %d' % self.app.modem_manager.mm_instance.pid)
                if self.app.modem_manager.mm_instance.is_running
                and self.app.modem_manager.mm_instance.pid
                else ''
            )
            self.mm_status_label.set_label(
                'Started'
                if self.app.modem_manager.mm_instance.is_running
                else 'Stopped'
            )
            self.mm_version_row.set_visible(
                self.app.modem_manager.mm_instance.is_running
            )
            self.mm_version_label.set_label(
                self.app.modem_manager.mm_instance.version
                if self.app.modem_manager.mm_instance.version
                else ''
            )

            self.detected_modems_group.set_visible(
                bool(self.app.modem_manager.mm_instance.modems.get_n_items())
            )

    def update_mm_debug_data(self, *args):
        if self.app.mm_debug_data:
            self.mm_debug_view.get_buffer().set_text(self.app.mm_debug_data)

    def update_udev_debug_data(self, *args):
        if self.app.udev_debug_data:
            self.udev_debug_view.get_buffer().set_text(
                self.app.udev_debug_data
            )

    def update_nusb_debug_data(self, *args):
        if self.app.nusb_debug_data:
            self.nusb_debug_view.get_buffer().set_text(
                self.app.nusb_debug_data
            )

    def update_spi_devices(self, *args):
        def visit(container: Gtk.Widget):
            item = container.get_first_child()
            while item:
                next_item = item.get_next_sibling()
                if isinstance(item, Adw.ExpanderRow):
                    self.spi_ports_group.remove(item)
                else:
                    visit(item)
                item = next_item

        visit(self.spi_ports_group)

        vid_pid_to_ports: Dict[str, List[SerialPort]] = defaultdict(list)

        for pos in range(self.app.device_scanner.spi_devices.get_n_items()):
            item = self.app.device_scanner.spi_devices.get_item(pos)

            vid_pid_to_ports[item.usb_vid_pid].append(item)

        for vid_pid, ports in vid_pid_to_ports.items():
            first_port = ports[0]

            main_row = Adw.ExpanderRow.new()
            main_row.set_expanded(True)
            main_row.set_title_selectable(True)
            main_row.set_title(
                '<b>%s %s</b> - %s'
                % (
                    GLib.markup_escape_text(first_port.usb_vendor, -1),
                    GLib.markup_escape_text(first_port.usb_product, -1),
                    GLib.markup_escape_text(first_port.usb_vid_pid, -1),
                )
            )

            for port in ports:
                port_row = Adw.ActionRow.new()
                port_row.set_title_selectable(True)
                port_row.set_subtitle_selectable(True)
                port_row.set_title(
                    '<b>%s</b>'
                    % (GLib.markup_escape_text(port.tty_device_path, -1))
                )
                port_row.set_subtitle(
                    (GLib.markup_escape_text(port.sysfs_device_path, -1))
                )

                main_row.add_row(port_row)

            self.spi_ports_group.add(main_row)

    def update_mm_modems(self, *args):
        def visit(container: Gtk.Widget):
            item = container.get_first_child()
            while item:
                next_item = item.get_next_sibling()
                if isinstance(item, Adw.ExpanderRow):
                    self.detected_modems_group.remove(item)
                else:
                    visit(item)
                item = next_item

        visit(self.detected_modems_group)

        for pos in range(
            self.app.modem_manager.mm_instance.modems.get_n_items()
        ):
            item = self.app.modem_manager.mm_instance.modems.get_item(pos)

            main_row = Adw.ExpanderRow.new()
            main_row.set_expanded(True)
            main_row.set_title_selectable(True)
            main_row.set_title(
                '<b>%s</b>' % GLib.markup_escape_text(item.modem_name, -1)
            )
            main_row.set_subtitle(
                'IMEI: %s | Firmware: %s'
                % (
                    GLib.markup_escape_text(item.modem_imei, -1),
                    GLib.markup_escape_text(item.modem_firmware, -1),
                )
            )
            for pos in range(item.ports.get_n_items()):
                port = item.ports.get_item(pos)

                port_title = port.device_path
                port_title += ' (type: %s)' % port.port_type
                if port.is_primary:
                    port_title += ' - Primary'

                port_row = Adw.ActionRow.new()
                port_row.set_title_selectable(True)
                port_row.set_title(GLib.markup_escape_text(port_title, -1))

                main_row.add_row(port_row)

            self.detected_modems_group.add(main_row)
