#!/usr/bin/env python3
from typing import List, Dict, Tuple, Optional
from collections import defaultdict
from logging import info

# Register resources
import diagng.utils.gresources

from diagng.gobject.mm_modem import ModemManagerModem
from diagng.gobject.mm_port import ModemManagerPort
from diagng.gobject.serial_port import SerialPort

# Based on https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#ui-from-graphical-designer

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
gi.require_version('GtkSource', '5')
from gi.repository import Gtk, Adw, Gdk, GLib, Gio, GtkSource


@Gtk.Template(resource_path='/com/p1security/diagng/diagng-autogenerated.ui')
class MyWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'

    app: 'MainApplication'
    adw_style_manager: Adw.StyleManager

    # UI panel: ModemManager

    mm_link_banner: Adw.ActionRow = Gtk.Template.Child()
    usb_link_banner: Adw.ActionRow = Gtk.Template.Child()
    spi_link_banner: Adw.ActionRow = Gtk.Template.Child()
    adb_link_banner: Adw.ActionRow = Gtk.Template.Child()

    mm_status_row: Adw.ActionRow = Gtk.Template.Child()
    mm_status_label: Gtk.Label = Gtk.Template.Child()
    mm_version_row: Adw.ActionRow = Gtk.Template.Child()
    mm_version_label: Gtk.Label = Gtk.Template.Child()

    detected_modems_group: Adw.PreferencesGroup = Gtk.Template.Child()
    spi_ports_group: Adw.PreferencesGroup = Gtk.Template.Child()

    mm_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    mm_debug_view: GtkSource
    mm_sourceview_buffer: GtkSource.Buffer

    # UI panel: USB

    usb_selection: Gio.ListStore = Gtk.Template.Child()

    udev_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    udev_debug_view: GtkSource.View
    udev_sourceview_buffer: GtkSource.Buffer

    nusb_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    nusb_debug_view: GtkSource.View
    nusb_sourceview_buffer: GtkSource.Buffer

    tokio_serial_debug_viewport: Adw.PreferencesGroup = Gtk.Template.Child()
    tokio_serial_debug_view: GtkSource.View
    tokio_serial_sourceview_buffer: GtkSource.Buffer

    # UI panel: SPI

    spi_selection: Gio.ListStore = Gtk.Template.Child()

    def __init__(self, app):
        super().__init__()

        self.app = app
        self.set_application(app)

        lang_manager = GtkSource.LanguageManager.new()

        # Build ModemManager debug SourceView

        self.mm_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.mm_debug_view = GtkSource.View.new_with_buffer(
            self.mm_sourceview_buffer
        )
        self.mm_debug_view.set_editable(False)
        self.mm_debug_viewport.set_child(self.mm_debug_view)

        # Build USB device tree view

        self.usb_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.device_scanner.usb_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        # Build SPI device tree view

        self.spi_selection.set_model(
            Gtk.TreeListModel.new(
                root=self.app.device_scanner.spi_device_tree,
                passthrough=False,
                autoexpand=True,
                create_func=lambda item: item.children,
            )
        )

        # Build UDev debug SourceView

        self.udev_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.udev_debug_view = GtkSource.View.new_with_buffer(
            self.udev_sourceview_buffer
        )
        self.udev_debug_view.set_editable(False)
        self.udev_debug_viewport.set_child(self.udev_debug_view)

        # Build nusb debug SourceView

        self.nusb_sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )

        self.nusb_debug_view = GtkSource.View.new_with_buffer(
            self.nusb_sourceview_buffer
        )
        self.nusb_debug_view.set_editable(False)
        self.nusb_debug_viewport.set_child(self.nusb_debug_view)

        # Build tokio-serial debug SourceView

        self.tokio_serial_sourceview_buffer = (
            GtkSource.Buffer.new_with_language(
                lang_manager.get_language('json')
            )
        )

        self.tokio_serial_debug_view = GtkSource.View.new_with_buffer(
            self.tokio_serial_sourceview_buffer
        )
        self.tokio_serial_debug_view.set_editable(False)
        self.tokio_serial_debug_viewport.set_child(
            self.tokio_serial_debug_view
        )

        # Monitor for dark mode changes

        self.adw_style_manager = Adw.StyleManager.get_default()
        self.sync_sourceview_theme()
        self.adw_style_manager.connect('notify', self.sync_sourceview_theme)

        # Connect actions

        self.connect_actions()

        # Connect signals

        self.app.device_scanner.spi_devices.connect(
            'items-changed', self.update_spi_devices
        )
        self.app.modem_manager.mm_instance.modems.connect(
            'items-changed', self.update_mm_modems
        )
        self.app.modem_manager.mm_instance.modems.connect(
            'items-changed', self.update_spi_devices
        )
        self.app.modem_manager.mm_instance.connect(
            'notify::is-running', self.update_daemon_statuses
        )
        self.app.diagmond_communicator.connect(
            'notify::bus-connected', self.update_daemon_statuses
        )
        self.app.modem_manager.mm_instance.connect(
            'notify', self.update_mm_instance
        )
        self.app.connect('notify::mm-debug-data', self.update_mm_debug_data)
        self.app.connect(
            'notify::udev-debug-data', self.update_udev_debug_data
        )
        self.app.connect(
            'notify::nusb-debug-data', self.update_nusb_debug_data
        )
        self.app.connect(
            'notify::tokio-serial-debug-data',
            self.update_tokio_serial_debug_data,
        )

        # Reset the default UI state

        self.mm_status_row.set_subtitle('Fetching information...')
        self.mm_status_label.set_label('')
        self.mm_version_label.set_label('')

        self.update_daemon_statuses()
        self.update_spi_devices()
        self.update_mm_modems()
        self.update_mm_instance()
        self.update_mm_debug_data()
        self.update_udev_debug_data()
        self.update_nusb_debug_data()
        self.update_tokio_serial_debug_data()

    def add_simple_action(
        self, name, callback, param_type: Optional[GLib.VariantType] = None
    ):

        action = Gio.SimpleAction.new(name, param_type)
        action.connect('activate', callback)
        self.add_action(action)

    def connect_actions(self):

        def copy_mm_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.mm_debug_data)

        self.add_simple_action('copy-mm-debug-info', copy_mm_debug_info)

        def copy_udev_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.udev_debug_data)

        self.add_simple_action('copy-udev-debug-info', copy_udev_debug_info)

        def copy_nusb_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.nusb_debug_data)

        self.add_simple_action('copy-nusb-debug-info', copy_nusb_debug_info)

        def copy_tokio_serial_debug_info(*args):
            clipboard = Gdk.Display.get_default().get_clipboard()
            clipboard.set(self.app.tokio_serial_debug_data)

        self.add_simple_action(
            'copy-tokio-serial-debug-info', copy_tokio_serial_debug_info
        )

    def update_daemon_statuses(self, *args):
        mm_running = self.app.modem_manager.mm_instance.is_running
        diagmond_running = self.app.diagmond_communicator.bus_connected
        # udev_reachable = True
        # adb_reachable = True

        self.mm_link_banner.set_title(
            'ModemManager Link: %s - diagmond status: %s'
            % (
                'ON' if mm_running else 'OFF',
                'ON' if diagmond_running else 'OFF',
            )
        )
        self.usb_link_banner.set_title(
            'UDev status: REACHABLE - diagmond status: %s'
            % ('ON' if diagmond_running else 'OFF')
        )
        self.spi_link_banner.set_title(
            'UDev status: REACHABLE - diagmond status: %s'
            % ('ON' if diagmond_running else 'OFF')
        )

    def sync_sourceview_theme(self, *args):
        is_dark_mode: bool = self.adw_style_manager.get_dark()

        color_scheme_manager = GtkSource.StyleSchemeManager.new()
        for scheme in color_scheme_manager.get_scheme_ids():
            is_dark_theme: bool = (
                'dark' in scheme or 'oblivion' in scheme or 'cobalt' in scheme
            )
            if is_dark_mode == is_dark_theme:
                self.mm_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.udev_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.nusb_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                self.tokio_serial_sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                break

    def update_mm_instance(self, *args):
        if self.app.modem_manager.mm_instance.initialized:
            self.mm_status_row.set_subtitle(
                ('PID %d' % self.app.modem_manager.mm_instance.pid)
                if self.app.modem_manager.mm_instance.is_running
                and self.app.modem_manager.mm_instance.pid
                else ''
            )
            self.mm_status_label.set_label(
                'Started'
                if self.app.modem_manager.mm_instance.is_running
                else 'Stopped'
            )
            self.mm_version_row.set_visible(
                self.app.modem_manager.mm_instance.is_running
            )
            self.mm_version_label.set_label(
                self.app.modem_manager.mm_instance.version
                if self.app.modem_manager.mm_instance.version
                else ''
            )

            self.detected_modems_group.set_visible(
                bool(self.app.modem_manager.mm_instance.modems.get_n_items())
            )

    def update_mm_debug_data(self, *args):
        if self.app.mm_debug_data:
            self.mm_debug_view.get_buffer().set_text(self.app.mm_debug_data)

    def update_udev_debug_data(self, *args):
        if self.app.udev_debug_data:
            self.udev_debug_view.get_buffer().set_text(
                self.app.udev_debug_data
            )

    def update_nusb_debug_data(self, *args):
        if self.app.nusb_debug_data:
            self.nusb_debug_view.get_buffer().set_text(
                self.app.nusb_debug_data
            )

    def update_tokio_serial_debug_data(self, *args):
        if self.app.tokio_serial_debug_data:
            self.tokio_serial_debug_view.get_buffer().set_text(
                self.app.tokio_serial_debug_data
            )

    def update_spi_devices(self, *args):
        def visit(container: Gtk.Widget):
            item = container.get_first_child()
            while item:
                next_item = item.get_next_sibling()
                if isinstance(item, Adw.ExpanderRow):
                    self.spi_ports_group.remove(item)
                else:
                    visit(item)
                item = next_item

        visit(self.spi_ports_group)

        vid_pid_to_ports: Dict[str, List[SerialPort]] = defaultdict(list)
        vid_pid_to_mm_obj: Dict[str, List[ModemManagerModem]] = defaultdict(
            list
        )
        dev_path_to_mm_obj: Dict[
            str, Tuple[ModemManagerPort, ModemManagerModem]
        ] = {}

        for pos in range(
            self.app.modem_manager.mm_instance.modems.get_n_items()
        ):
            item = self.app.modem_manager.mm_instance.modems.get_item(pos)

            for pos in range(item.ports.get_n_items()):
                port = item.ports.get_item(pos)

                dev_path_to_mm_obj[port.device_path] = (port, item)

        for pos in range(self.app.device_scanner.spi_devices.get_n_items()):
            item = self.app.device_scanner.spi_devices.get_item(pos)

            vid_pid_to_ports[item.usb_vid_pid].append(item)

            if item.tty_device_path in dev_path_to_mm_obj:
                mm_port, mm_modem = dev_path_to_mm_obj[item.tty_device_path]
                vid_pid_to_mm_obj[item.usb_vid_pid] = mm_modem

        for vid_pid, ports in vid_pid_to_ports.items():
            first_port = ports[0]

            main_row = Adw.ExpanderRow.new()
            main_row.set_expanded(True)
            main_row.set_title_selectable(True)
            main_row.set_title(
                '<b>%s %s</b> - %s'
                % (
                    GLib.markup_escape_text(first_port.usb_vendor, -1),
                    GLib.markup_escape_text(first_port.usb_product, -1),
                    GLib.markup_escape_text(first_port.usb_vid_pid, -1),
                )
            )

            if first_port.usb_vid_pid in vid_pid_to_mm_obj:
                mm_modem = vid_pid_to_mm_obj[first_port.usb_vid_pid]

                main_row.set_subtitle(
                    'IMEI: %s | Firmware: %s'
                    % (
                        GLib.markup_escape_text(mm_modem.modem_imei, -1),
                        GLib.markup_escape_text(mm_modem.modem_firmware, -1),
                    )
                )

            for port in ports:
                port_row = Adw.ActionRow.new()
                port_row.set_title_selectable(True)
                port_row.set_subtitle_selectable(True)
                port_row.set_title(
                    '<b>%s</b>'
                    % (GLib.markup_escape_text(port.tty_device_path, -1))
                )
                port_row.set_tooltip_text(port.sysfs_device_path)

                connect_btn = Gtk.Button()
                connect_btn.set_label('Connect')
                connect_btn.add_css_class('pill')
                connect_btn.add_css_class('suggested-action')

                # Annotate devices with USB interface

                subtitle = 'Interface: %s' % port.usb_interface

                # Don't propose to lock devices which are not
                # known from ModemManager

                if port.tty_device_path in dev_path_to_mm_obj:
                    mm_port, mm_modem = dev_path_to_mm_obj[
                        port.tty_device_path
                    ]

                    lock_port_btn = Gtk.Button()
                    lock_port_btn.set_label(
                        'Lock port'
                        if not mm_modem.inhibited
                        else 'Unlock port'
                    )
                    lock_port_btn.add_css_class('pill')
                    port_row.add_suffix(lock_port_btn)

                    if not mm_modem.inhibited:
                        lock_port_btn.connect(
                            'clicked',
                            self.lock_mm_port,
                            mm_modem,
                            mm_port,
                        )

                    else:
                        lock_port_btn.connect(
                            'clicked',
                            self.unlock_mm_port,
                            mm_modem,
                            mm_port,
                        )

                    # Annotate devices with ModemManager function

                    subtitle += ' | Type: ' + mm_port.port_type

                    connect_btn.connect(
                        'clicked',
                        self.connect_mm_spi_port,
                        port,
                        mm_modem,
                        mm_port,
                    )

                else:
                    connect_btn.connect(
                        'clicked',
                        self.connect_non_mm_spi_port,
                        port,
                    )

                port_row.set_subtitle(GLib.markup_escape_text(subtitle, -1))

                port_row.add_suffix(connect_btn)

                main_row.add_row(port_row)

            self.spi_ports_group.add(main_row)

    def lock_mm_port(
        self,
        target: Gtk.Button,
        mm_modem: ModemManagerModem,
        mm_port: ModemManagerPort,
    ):
        info(
            'lock_mm_port called on %s / %s'
            % (mm_modem.modem_device_id, mm_port.device_path)
        )

        if self.app.diagmond_communicator.bus_connected:
            if self.app.diagmond_communicator.proxy.LockMMDevice(
                '(s)', mm_modem.modem_device_id
            ):
                mm_modem.inhibited = True

    def unlock_mm_port(
        self,
        target: Gtk.Button,
        mm_modem: ModemManagerModem,
        mm_port: ModemManagerPort,
    ):
        info(
            'lock_mm_unport called on %s / %s'
            % (mm_modem.modem_device_id, mm_port.device_path)
        )

        if self.app.diagmond_communicator.bus_connected:
            if self.app.diagmond_communicator.proxy.ReleaseMMDevice(
                '(s)', mm_modem.modem_device_id
            ):
                mm_modem.inhibited = False

    def connect_mm_spi_port(
        self,
        target: Gtk.Button,
        port: SerialPort,
        mm_modem: ModemManagerModem,
        mm_port: ModemManagerPort,
    ):
        info('connect_mm_spi_port called on %s' % port.tty_device_path)  # TODO

    def connect_non_mm_spi_port(self, target: Gtk.Button, port: SerialPort):
        info(
            'connect_non_mm_spi_port called on %s' % port.tty_device_path
        )  # TODO

    def update_mm_modems(self, *args):
        def visit(container: Gtk.Widget):
            item = container.get_first_child()
            while item:
                next_item = item.get_next_sibling()
                if isinstance(item, Adw.ExpanderRow):
                    self.detected_modems_group.remove(item)
                else:
                    visit(item)
                item = next_item

        visit(self.detected_modems_group)

        for pos in range(
            self.app.modem_manager.mm_instance.modems.get_n_items()
        ):
            item = self.app.modem_manager.mm_instance.modems.get_item(pos)

            main_row = Adw.ExpanderRow.new()
            main_row.set_expanded(True)
            main_row.set_title_selectable(True)
            main_row.set_title(
                '<b>%s</b>' % GLib.markup_escape_text(item.modem_name, -1)
            )
            main_row.set_subtitle(
                'IMEI: %s | Firmware: %s'
                % (
                    GLib.markup_escape_text(item.modem_imei, -1),
                    GLib.markup_escape_text(item.modem_firmware, -1),
                )
            )
            for pos in range(item.ports.get_n_items()):
                port = item.ports.get_item(pos)

                port_title = port.device_path
                port_title += ' (type: %s)' % port.port_type
                if port.is_primary:
                    port_title += ' - Primary'

                port_row = Adw.ActionRow.new()
                port_row.set_title_selectable(True)
                port_row.set_title(GLib.markup_escape_text(port_title, -1))

                main_row.add_row(port_row)

            self.detected_modems_group.add(main_row)
