#!/usr/bin/env python3
from os.path import dirname, realpath, exists, join
from os import stat, scandir, access, W_OK
from typing import Optional
from subprocess import run
from shutil import which

# Based on https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#ui-from-graphical-designer

import sys
import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, GObject, Gio

SCRIPT_DIR = dirname(realpath(__file__))
ASSETS_DIR = realpath(join(SCRIPT_DIR, 'assets'))
RESOURCES_PATH = realpath(join(ASSETS_DIR, 'qcdm-lock-manager.gresource'))


class MyApp(Adw.Application):
    kernel_path: Optional[str] = None

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.connect('startup', self.on_startup)
        self.connect('activate', self.on_activate)

    def on_startup(self, app, *args):
        self.window = MyWindow()
        self.window.set_application(self)

        # Application will close once it no longer has active windows attached to it

        self.window.present()

    def on_activate(self, app):
        self.window.present()

        # NEXT TODO ==>
        # FILL IN THE TREE VIEW WITH SAMPLE INFORMATION

        # Cf. https://github.com/timlau/yumex-ng/blob/09f15091a2f0f3a8c189bbd4dc59016a80e2debf/yumex/ui/transaction_result.py
        # Cf. https://github.com/timlau/yumex-ng/blob/09f15091a2f0f3a8c189bbd4dc59016a80e2debf/data/ui/transaction_result.blp
        # Cf. too
        # https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#using-gridview


# Create a templated window object, in order
# to parse the Cambalache-produced UI file

if not exists(RESOURCES_PATH) or (
    access(RESOURCES_PATH, W_OK)
    and which('blueprint-compiler')
    and which('glib-compile-resources')
    and max(meta.stat().st_mtime for meta in scandir(ASSETS_DIR))
    > stat(RESOURCES_PATH).st_mtime
):
    run(
        [
            'blueprint-compiler',
            'compile',
            '--output',
            'qcdm-lock-manager-autogenerated.ui',
            'qcdm-lock-manager.blp',
        ],
        cwd=ASSETS_DIR,
    )
    run(['glib-compile-resources', RESOURCES_PATH + '.xml'], cwd=ASSETS_DIR)

Gio.resources_register(Gio.resource_load(RESOURCES_PATH))


@Gtk.Template(
    resource_path='/com/p1security/qcdm-lock-manager/qcdm-lock-manager-autogenerated.ui'
)
class MyWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'


def main():
    app = MyApp(application_id='com.p1security.qcdm-lock-manager')
    app.run(sys.argv)


if __name__ == '__main__':
    main()
