#!/usr/bin/env python3
from os.path import dirname, realpath, exists, join
from os import stat, scandir, access, W_OK
from subprocess import run
from shutil import which

# Based on https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#ui-from-graphical-designer

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw, Gio

SCRIPT_DIR = dirname(realpath(__file__))
ASSETS_DIR = realpath(join(SCRIPT_DIR, 'assets'))
RESOURCES_PATH = realpath(join(ASSETS_DIR, 'diagng.gresource'))


# Create a templated window object, in order
# to parse the Cambalache-produced UI file

if not exists(RESOURCES_PATH) or (
    access(RESOURCES_PATH, W_OK)
    and which('blueprint-compiler')
    and which('glib-compile-resources')
    and max(meta.stat().st_mtime for meta in scandir(ASSETS_DIR))
    > stat(RESOURCES_PATH).st_mtime
):
    run(
        [
            'blueprint-compiler',
            'compile',
            '--output',
            'diagng-autogenerated.ui',
            'diagng.blp',
        ],
        cwd=ASSETS_DIR,
    )
    run(['glib-compile-resources', RESOURCES_PATH + '.xml'], cwd=ASSETS_DIR)

Gio.resources_register(Gio.resource_load(RESOURCES_PATH))


@Gtk.Template(resource_path='/com/p1security/diagng/diagng-autogenerated.ui')
class MyWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'
