#!/usr/bin/env python3
from os.path import dirname, realpath, exists, join
from os import stat, scandir, access, W_OK
from subprocess import run
from shutil import which

from diagng.gobject.mm_modem import ModemManagerModem

# Based on https://github.com/Taiko2k/GTK4PythonTutorial?tab=readme-ov-file#ui-from-graphical-designer

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
gi.require_version('Pango', '1.0')
gi.require_version('GtkSource', '5')
from gi.repository import Gtk, Adw, GLib, Gio, GtkSource, Pango

SCRIPT_DIR = dirname(realpath(__file__))
ASSETS_DIR = realpath(join(SCRIPT_DIR, 'assets'))
RESOURCES_PATH = realpath(join(ASSETS_DIR, 'diagng.gresource'))


# Create a templated window object, in order
# to parse the Cambalache-produced UI file

if not exists(RESOURCES_PATH) or (
    access(RESOURCES_PATH, W_OK)
    and which('blueprint-compiler')
    and which('glib-compile-resources')
    and max(meta.stat().st_mtime for meta in scandir(ASSETS_DIR))
    > stat(RESOURCES_PATH).st_mtime
):
    run(
        [
            'blueprint-compiler',
            'compile',
            '--output',
            'diagng-autogenerated.ui',
            'diagng.blp',
        ],
        cwd=ASSETS_DIR,
    )
    run(['glib-compile-resources', RESOURCES_PATH + '.xml'], cwd=ASSETS_DIR)

Gio.resources_register(Gio.resource_load(RESOURCES_PATH))


@Gtk.Template(resource_path='/com/p1security/diagng/diagng-autogenerated.ui')
class MyWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'

    app: 'MainApplication'

    mm_debug_group: Adw.PreferencesGroup = Gtk.Template.Child()
    mm_debug_view: GtkSource
    sourceview_css_provider: Gtk.CssProvider
    sourceview_style_manager: Adw.StyleManager

    mm_status_row: Adw.ActionRow = Gtk.Template.Child()
    mm_status_label: Gtk.Label = Gtk.Template.Child()
    mm_version_row: Adw.ActionRow = Gtk.Template.Child()
    mm_version_label: Gtk.Label = Gtk.Template.Child()

    detected_modems_group: Adw.PreferencesGroup = Gtk.Template.Child()

    def __init__(self, app):
        super().__init__()

        self.app = app
        self.set_application(app)

        lang_manager = GtkSource.LanguageManager.new()

        self.sourceview_buffer = GtkSource.Buffer.new_with_language(
            lang_manager.get_language('json')
        )
        self.sourceview_style_manager = Adw.StyleManager.get_default()

        self.mm_debug_view = GtkSource.View.new_with_buffer(
            self.sourceview_buffer
        )
        self.mm_debug_view.set_size_request(-1, 200)
        self.mm_debug_group.add(self.mm_debug_view)

        self.sourceview_css_provider = Gtk.CssProvider()
        style_context = self.mm_debug_view.get_style_context()
        style_context.add_provider(
            self.sourceview_css_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION,
        )

        self.sync_sourceview_theme()
        self.sourceview_style_manager.connect(
            'notify', self.sync_sourceview_theme
        )

        self.mm_status_row.set_subtitle('Fetching information...')
        self.mm_status_label.set_label('')
        self.mm_version_label.set_label('')

        self.detected_modems_group.bind_model(
            self.app.mm_instance.modems, self.create_mm_modem
        )

        self.app.mm_instance.connect('notify', self.update_mm_instance)
        self.app.connect('notify', self.update_mm_debug_data)

        self.update_mm_instance()
        self.update_mm_debug_data()

    def sync_sourceview_theme(self, *args):
        is_dark_mode: bool = self.sourceview_style_manager.get_dark()

        color_scheme_manager = GtkSource.StyleSchemeManager.new()
        for scheme in color_scheme_manager.get_scheme_ids():
            is_dark_theme: bool = (
                'dark' in scheme or 'oblivion' in scheme or 'cobalt' in scheme
            )
            if is_dark_mode == is_dark_theme:
                self.sourceview_buffer.set_style_scheme(
                    color_scheme_manager.get_scheme(scheme)
                )
                break

        monospace_font = Pango.FontDescription.from_string(
            self.sourceview_style_manager.get_monospace_font_name()
        )

        self.sourceview_css_provider.load_from_string(
            'textview { font-family: "%s"; font-size: %g%s; }'
            % (
                monospace_font.get_family(),
                monospace_font.get_size() / Pango.SCALE,
                'px' if monospace_font.get_size_is_absolute() else 'pt',
            )
        )

    def update_mm_instance(self, *args):
        if self.app.mm_instance.initialized:
            self.mm_status_row.set_subtitle(
                ('PID %d' % self.app.mm_instance.pid)
                if self.app.mm_instance.is_running and self.app.mm_instance.pid
                else ''
            )
            self.mm_status_label.set_label(
                'Started' if self.app.mm_instance.is_running else 'Stopped'
            )
            self.mm_version_row.set_visible(self.app.mm_instance.is_running)
            self.mm_version_label.set_label(
                self.app.mm_instance.version
                if self.app.mm_instance.version
                else ''
            )

            self.detected_modems_group.set_visible(
                bool(self.app.mm_instance.modems.get_n_items())
            )

    def update_mm_debug_data(self, *args):
        if self.app.mm_debug_data:
            self.mm_debug_view.get_buffer().set_text(self.app.mm_debug_data)

    def create_mm_modem(self, item: ModemManagerModem) -> Adw.ExpanderRow:
        main_row = Adw.ExpanderRow.new()
        main_row.set_expanded(True)
        main_row.set_title_selectable(True)
        main_row.set_title(
            '<b>%s</b>' % GLib.markup_escape_text(item.modem_name, -1)
        )
        main_row.set_subtitle(
            'IMEI: %s | Firmware: %s'
            % (
                GLib.markup_escape_text(item.modem_imei, -1),
                GLib.markup_escape_text(item.modem_firmware, -1),
            )
        )
        for pos in range(item.ports.get_n_items()):
            port = item.ports.get_item(pos)

            port_title = port.device_path
            port_title += ' (type: %s)' % port.port_type
            if port.is_primary:
                port_title += ' - Primary'

            port_row = Adw.ActionRow.new()
            port_row.set_title_selectable(True)
            port_row.set_title(GLib.markup_escape_text(port_title, -1))

            main_row.add_row(port_row)

        return main_row
