[package]
name = "diagmond"
version = "0.1.0"
edition = "2024"

[dependencies]
fern = "0.7.1"
futures-util = "0.3.32"
glib = "0.22.7"
hex = "0.4.3"
humantime = "2.3.0"
inotify = "0.11.2"
log = { version = "0.4.32", features = ["kv", "kv_std"] }
nusb = { version = "0.2.3", features = ["tokio"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["preserve_order"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "process", "sync"] }
tokio-serial = { version = "5.5.0", features = ["libudev", "rt", "codec", "serde"] }
zbus = { version = "5.17.0", default-features = false, features = ["tokio"] }
zvariant = "5.12.0"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.31.3", features = ["user"] }
